### ISSUE TITLE
服务端外网运行后，客户端之间不能通信。

### ISSUE THREAD

**Issue by andy-da** [pannzh/P2P-Over-MiddleBoxes-Demo#2]
程序运行后，客户端A，B通信不成功。
测试环境，服务端C在公网上，客户端A在机器1虚拟机下运行，客户端B在机器2虚拟机下运行，连的手机wifi热点。
求教，这程序有验证成功过吗？

![p2p_nat_udp_failed](https://user-images.githubusercontent.com/7381952/33985382-65654cce-e0f5-11e7-99ac-eb2977bda861.png)

**Comment by evilpan** [comment]
这种情况下, A和B在同一个NAT之后, 若要A,B之间可以打洞, 则该NAT需要支持回环传输(loopback transmission)才可以.

**Comment by andy-da** [comment]
怎样设置NAT支持回环传输loopback transmission。

http://m.blog.csdn.net/bobbob32/article/details/78778762
这篇博文提到了回环传输。

**Comment by evilpan** [comment]
如果是个人的路由器可以通过登录管理页面设置, 一般Linux下都可以通过iptable来管理loopback:
```
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT
```
