### ISSUE TITLE
 客户端Port Rristrict Cone NAT服务端 Full Cone NAT，打洞不成功

### ISSUE THREAD

**Issue by ggandycong** [pannzh/P2P-Over-MiddleBoxes-Demo#4]
测试过两个不同局域网，打洞不成功。两个相同局域网（同一个nat之后）也是不成功。
没成功问题表现在，当clientA主动向clientB发送一个punch命令时候。然后再发给服务端，服务端转发给clientB，clientB这时候发送一个消息给clientA。但是clientA没有收到消息（问题在这里，这个是同一个nat之后）。（客户端Port Rristrict Cone NAT服务端 Full Cone NAT），请问大概是哪里问的问题呢。
对于这个，不是很理解。
`If two of your peers are both behind the same NAT, this NAT must support LOOPBACK TRANSMISSION to forward messages. You can test it by using the utils(udp_server/udp_client) in tools`

**Comment by evilpan** [comment]
同一个NAT之后的两个客户端打洞, 该NAT是否支持`loopback transmission`?

**Comment by ggandycong** [comment]
我跑了tools下udp_server/udp_client。 客户端发送的数据，服务端能够收到（内容是乱码）。不知道这样是否支持loopback tranmission。 我对这个不太了解。假如不支持的话，有什么方法改进吗？ （或者目前哪些库尽可能比较完美支持两个局域网通信？ ）

**Comment by ggandycong** [comment]
刘德聪，已经收到你的邮件，请你放心
祝你生活愉快，笑口常开
