### ISSUE TITLE
你好！

### ISSUE THREAD

**Issue by tiankaijin** [pannzh/P2P-Over-MiddleBoxes-Demo#6]
请教一下，怎样正确使用tools里面的udp_server和udp_client检测Nat是否支持回环传输（FULL CONE NAT）?
---------------------------------------
A机器的内网地址（192.168.1.14）
B机器的内网地址（192.168.1.43）
---------------------------------------
我在A（192.168.1.14）机器上运行：udp_server 8888，
在B（192.168.1.43）机器上运行udp_client；然后运行sendto 192.168.1.14:8888 hello
此时A是可以收到hello的。但是我感觉我测试的方式有问题，请问是这样测试的吗，如果不是，您能不能把正确的方式跟我说一下？

**Comment by evilpan** [comment]
@tiankaijin 你好，这两个程序就是单纯的udp client和server，用来测试手工打洞的。
要测试回环传输，可以：
1. 在公网或者上层网络启动udp_server
2. 在内网使用udp_client A、B发送数据到udp_server，查看二者经过NAT的出口UDP地址和端口
3. A向B的出口UDP地址对发送数据，打通NAT。
4. B向A的出口UDP地址对发送数据，若A能收到则支持回环，否则不支持，或者不是CONE NAT。

如果中间经过多层路由，需要每层路由器都支持回环。
